#:schema node_modules/wrangler/config-schema.json
name = "sublink-worker0631"
main = "src/index.js"
compatibility_date = "2024-07-24"
compatibility_flags = ["nodejs_compat"]

kv_namespaces = [
  { binding = "SUBLINK_KV", id = "878376cae01b4975bc1c4505f3b262e1" }
]
